# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               losmescaleros
tagline:             'Another software blog thing'
description:         'Rolling my head on the keyboard until something good happens'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mitchell Neville
  url:               https://losmescaleros.github.io
  email:             losmescaleros@gmail.com

# Custom vars
version:             1.0.0
